### ISSUE TITLE
PIR Pin not specified

### ISSUE THREAD

**Issue by jaajee** [rgrokett/ESP8266_PIRv2#3]
In your v2 code you haven't specified the PIR sensor pin, how ESP will detect the motion?

**Comment by rgrokett** [comment]
Deep Sleep mode works differently from regular GPIO monitoring. 
Normally, the software is running in a loop watching for a GPIO event. But this means the ESP is active (and using a fair amount of power.)

But with Deep Sleep, the GPIO pin is controlling the ESP module itself, with the hardware and the program completely halted while in deep sleep, so the software doesn't need to monitor the PIR.  Only the PIR is still "awake". Motion on the PIR causes a reset (via the transistor) of the ESP8266 itself, causing it to effectively reboot. This starts the software running again which sends the message via WiFi, then resets the deep sleep trigger and halts the processor. The software really doesn't care what caused the ESP to start running again, it just sends a message every time it wakes up.

The difference in power drain is significant. A set of 3 AA batteries last only a week or two with "normal mode" running, but will last 6 months or more using deep sleep.

You can see the hardware design and the ESP's GPIO pin 16 used by deep sleep on page 7 of the PDF document.
